# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('homeTeamName', models.CharField(max_length=200)),
                ('awayTeamName', models.CharField(max_length=200)),
                ('goalsAwayTeam', models.IntegerField()),
                ('goalsHomeTeam', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('competitionId', models.IntegerField()),
                ('opponent', models.CharField(max_length=200)),
                ('gameType', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
