# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='matchday',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
