# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0002_fixture_matchday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='goalsAwayTeam',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='goalsHomeTeam',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='matchday',
            field=models.IntegerField(default=0),
        ),
    ]
