# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-07 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0003_auto_20180306_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='competitionId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='goalsAwayTeam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='goalsHomeTeam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='matchday',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
