# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0004_auto_20180306_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
