# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0006_auto_20180312_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtotal',
            name='matchday',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
