# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0007_auto_20180312_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointTotal',
        ),
        migrations.AddField(
            model_name='fixture',
            name='pointTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
