# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-16 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0008_auto_20180313_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='pointTotal',
        ),
    ]
