# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-17 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0009_remove_fixture_pointtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='season',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
