# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-17 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0010_fixture_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=200)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('goalDifference', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('crestURL', models.CharField(max_length=200)),
            ],
        ),
    ]
