# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-05 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0012_standing_matchesplayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
